import os
import json
import stripe
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

stripe.api_key = os.getenv("STRIPE_SECRET_KEY", "").strip()

class CheckoutItem(BaseModel):
    name: str
    price: float
    image: str

@app.post("/api/checkout")
async def create_checkout_session(item: CheckoutItem):
    try:
        session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=[{
                'price_data': {
                    'currency': 'usd',
                    'product_data': {
                        'name': item.name,
                        'images': [item.image] if item.image else [],
                    },
                    'unit_amount': int(item.price * 100),
                },
                'quantity': 1,
            }],
            mode='payment',
            success_url='https://trendingabyss.com/?checkout=success',
            cancel_url='https://trendingabyss.com/',
        )
        return {"url": session.url}
    except Exception as e:
        return {"error": str(e)}

@app.get("/api/matrix")
async def get_matrix():
    try:
        # Instantly load the pre-audited catalog generated by your offline agent
        with open("matrix_catalog.json", "r") as f:
            return json.load(f)
    except Exception as e:
        # If the file hasn't been uploaded yet, show a safe standby message instead of crashing
        return [{"sku": "STANDBY", "name": "AI AGENT COMPILING CATALOG", "price": 0.0, "stock_count": 0, "hero_image": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800", "images": [], "shippingText": "PLEASE STAND BY", "storefront": "Tech & Mobile Gear", "specs": {}}]
